variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

before_script:
  - echo "Run this before every script."

  
stages:
  - build
  - test

builder:
  stage: build
  script:
    - echo "I am building something"
  tags: [android30]

CompileCPP:
  stage: test
  script:
    - echo "Compiling C++ code..."
    - cd app/src/main/cpp; g++ main.cpp
    #- ls -l com/example/knightsslabyrinth/MainActivity.class
  tags: [c++-17]

JunitTestGradle:
  stage: test
  script:
    - echo "Using gradle to run JUnit tests..."
    - ./gradlew -Pci --console=plain :app:testDebugUnitTest --tests "com.example.knightsslabyrinth.*"
  artifacts:
    paths:
      - app/build/test-results/testDebugUnitTest
    reports:
      junit: app/build/test-results/testDebugUnitTest/TEST-*.xml
  tags: [android30]
